/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_botn365_main_WootingAnalogWrapper */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper
#define _Included_com_github_botn365_main_WootingAnalogWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogInitialise
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogInitialise
  (JNIEnv *, jclass);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogIsInitialised
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogIsInitialised
  (JNIEnv *, jclass);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogUnisialise
 * Signature: ()Lcom/github/botn365/main/WootingAnalogWrapper/WootingAnalogResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogUnisialise
  (JNIEnv *, jclass);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogSetKeycode
 * Signature: (I)Lcom/github/botn365/main/WootingAnalogWrapper/WootingAnalogResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogSetKeycode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogReadAnalog
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogReadAnalog
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogReadAnalogDevice
 * Signature: (IJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogReadAnalogDevice
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogGetConnectedDevicesInfo
 * Signature: ([Lcom/github/botn365/main/WootingAnalogWrapper/WootingAnalogDeviceInfoFFI;)I
 */
JNIEXPORT jint JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogGetConnectedDevicesInfo
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogReadFullBuffer
 * Signature: ([S[F)I
 */
JNIEXPORT jint JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogReadFullBuffer
  (JNIEnv *, jclass, jshortArray, jfloatArray);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogReadFullBufferDevice
 * Signature: ([S[FJ)I
 */
JNIEXPORT jint JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogReadFullBufferDevice
  (JNIEnv *, jclass, jshortArray, jfloatArray, jlong);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogSetDeviceEventCb
 * Signature: (Lcom/github/botn365/main/WootingAnalogWrapper/DeviceEventCallback;)Lcom/github/botn365/main/WootingAnalogWrapper/WootingAnalogResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogSetDeviceEventCb
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_botn365_main_WootingAnalogWrapper
 * Method:    wootingAnalogClearDeviceEventCb
 * Signature: ()Lcom/github/botn365/main/WootingAnalogWrapper/WootingAnalogResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_botn365_main_WootingAnalogWrapper_wootingAnalogClearDeviceEventCb
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_botn365_main_WootingAnalogWrapper_WootingAnalogResult */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogResult
#define _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceEventType */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceEventType
#define _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceEventType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceType */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceType
#define _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceInfoFFI */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceInfoFFI
#define _Included_com_github_botn365_main_WootingAnalogWrapper_WootingAnalogDeviceInfoFFI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_botn365_main_WootingAnalogWrapper_DeviceEventCallback */

#ifndef _Included_com_github_botn365_main_WootingAnalogWrapper_DeviceEventCallback
#define _Included_com_github_botn365_main_WootingAnalogWrapper_DeviceEventCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
